name: speclab
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  animate_do: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/Logo_Landscape_Trsp.png
    - assets/images/pc_illustration.png
    - assets/images/welcomepage_bg.png
    - assets/images/bg.png
    - assets/images/speclab.png
    - assets/images/google_logo.png

  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  fonts:
     - family: Alexandria
       fonts:
          - asset: assets/fonts/Alexandria-Bold-BF6690948c16117.ttf

     - family: Alexandria-Light
       fonts:
         - asset: assets/fonts/Alexandria-Light-BF66909490125d0.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

